repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        # stages: [manual]  # Only run when explicitly called, not on commit

-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest --cov=src/pyhearingai --cov-report=term-missing --cov-fail-under=1 -k 'not test_whisper_openai_transcriber_basic'
        language: system
        pass_filenames: false
        always_run: true
        # stages: [manual]  # Only run when explicitly called, not on commit
